# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.19

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Disable VCS-based implicit rules.
% : %,v


# Disable VCS-based implicit rules.
% : RCS/%


# Disable VCS-based implicit rules.
% : RCS/%,v


# Disable VCS-based implicit rules.
% : SCCS/s.%


# Disable VCS-based implicit rules.
% : s.%


.SUFFIXES: .hpux_make_needs_suffix_list


# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/daniel/cpFEM

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/daniel/cpFEM

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/daniel/cpFEM/CMakeFiles /home/daniel/cpFEM//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/daniel/cpFEM/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named c_pFEM

# Build rule for target.
c_pFEM: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 c_pFEM
.PHONY : c_pFEM

# fast build rule for target.
c_pFEM/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/c_pFEM.dir/build.make CMakeFiles/c_pFEM.dir/build
.PHONY : c_pFEM/fast

cpFEM.o: cpFEM.cpp.o

.PHONY : cpFEM.o

# target to build an object file
cpFEM.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/c_pFEM.dir/build.make CMakeFiles/c_pFEM.dir/cpFEM.cpp.o
.PHONY : cpFEM.cpp.o

cpFEM.i: cpFEM.cpp.i

.PHONY : cpFEM.i

# target to preprocess a source file
cpFEM.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/c_pFEM.dir/build.make CMakeFiles/c_pFEM.dir/cpFEM.cpp.i
.PHONY : cpFEM.cpp.i

cpFEM.s: cpFEM.cpp.s

.PHONY : cpFEM.s

# target to generate assembly for a file
cpFEM.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/c_pFEM.dir/build.make CMakeFiles/c_pFEM.dir/cpFEM.cpp.s
.PHONY : cpFEM.cpp.s

create.o: create.cpp.o

.PHONY : create.o

# target to build an object file
create.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/c_pFEM.dir/build.make CMakeFiles/c_pFEM.dir/create.cpp.o
.PHONY : create.cpp.o

create.i: create.cpp.i

.PHONY : create.i

# target to preprocess a source file
create.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/c_pFEM.dir/build.make CMakeFiles/c_pFEM.dir/create.cpp.i
.PHONY : create.cpp.i

create.s: create.cpp.s

.PHONY : create.s

# target to generate assembly for a file
create.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/c_pFEM.dir/build.make CMakeFiles/c_pFEM.dir/create.cpp.s
.PHONY : create.cpp.s

draw.o: draw.cpp.o

.PHONY : draw.o

# target to build an object file
draw.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/c_pFEM.dir/build.make CMakeFiles/c_pFEM.dir/draw.cpp.o
.PHONY : draw.cpp.o

draw.i: draw.cpp.i

.PHONY : draw.i

# target to preprocess a source file
draw.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/c_pFEM.dir/build.make CMakeFiles/c_pFEM.dir/draw.cpp.i
.PHONY : draw.cpp.i

draw.s: draw.cpp.s

.PHONY : draw.s

# target to generate assembly for a file
draw.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/c_pFEM.dir/build.make CMakeFiles/c_pFEM.dir/draw.cpp.s
.PHONY : draw.cpp.s

fields.o: fields.cpp.o

.PHONY : fields.o

# target to build an object file
fields.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/c_pFEM.dir/build.make CMakeFiles/c_pFEM.dir/fields.cpp.o
.PHONY : fields.cpp.o

fields.i: fields.cpp.i

.PHONY : fields.i

# target to preprocess a source file
fields.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/c_pFEM.dir/build.make CMakeFiles/c_pFEM.dir/fields.cpp.i
.PHONY : fields.cpp.i

fields.s: fields.cpp.s

.PHONY : fields.s

# target to generate assembly for a file
fields.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/c_pFEM.dir/build.make CMakeFiles/c_pFEM.dir/fields.cpp.s
.PHONY : fields.cpp.s

linear_aux.o: linear_aux.cpp.o

.PHONY : linear_aux.o

# target to build an object file
linear_aux.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/c_pFEM.dir/build.make CMakeFiles/c_pFEM.dir/linear_aux.cpp.o
.PHONY : linear_aux.cpp.o

linear_aux.i: linear_aux.cpp.i

.PHONY : linear_aux.i

# target to preprocess a source file
linear_aux.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/c_pFEM.dir/build.make CMakeFiles/c_pFEM.dir/linear_aux.cpp.i
.PHONY : linear_aux.cpp.i

linear_aux.s: linear_aux.cpp.s

.PHONY : linear_aux.s

# target to generate assembly for a file
linear_aux.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/c_pFEM.dir/build.make CMakeFiles/c_pFEM.dir/linear_aux.cpp.s
.PHONY : linear_aux.cpp.s

linear_vect_to_field.o: linear_vect_to_field.cpp.o

.PHONY : linear_vect_to_field.o

# target to build an object file
linear_vect_to_field.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/c_pFEM.dir/build.make CMakeFiles/c_pFEM.dir/linear_vect_to_field.cpp.o
.PHONY : linear_vect_to_field.cpp.o

linear_vect_to_field.i: linear_vect_to_field.cpp.i

.PHONY : linear_vect_to_field.i

# target to preprocess a source file
linear_vect_to_field.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/c_pFEM.dir/build.make CMakeFiles/c_pFEM.dir/linear_vect_to_field.cpp.i
.PHONY : linear_vect_to_field.cpp.i

linear_vect_to_field.s: linear_vect_to_field.cpp.s

.PHONY : linear_vect_to_field.s

# target to generate assembly for a file
linear_vect_to_field.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/c_pFEM.dir/build.make CMakeFiles/c_pFEM.dir/linear_vect_to_field.cpp.s
.PHONY : linear_vect_to_field.cpp.s

move.o: move.cpp.o

.PHONY : move.o

# target to build an object file
move.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/c_pFEM.dir/build.make CMakeFiles/c_pFEM.dir/move.cpp.o
.PHONY : move.cpp.o

move.i: move.cpp.i

.PHONY : move.i

# target to preprocess a source file
move.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/c_pFEM.dir/build.make CMakeFiles/c_pFEM.dir/move.cpp.i
.PHONY : move.cpp.i

move.s: move.cpp.s

.PHONY : move.s

# target to generate assembly for a file
move.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/c_pFEM.dir/build.make CMakeFiles/c_pFEM.dir/move.cpp.s
.PHONY : move.cpp.s

number.o: number.cpp.o

.PHONY : number.o

# target to build an object file
number.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/c_pFEM.dir/build.make CMakeFiles/c_pFEM.dir/number.cpp.o
.PHONY : number.cpp.o

number.i: number.cpp.i

.PHONY : number.i

# target to preprocess a source file
number.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/c_pFEM.dir/build.make CMakeFiles/c_pFEM.dir/number.cpp.i
.PHONY : number.cpp.i

number.s: number.cpp.s

.PHONY : number.s

# target to generate assembly for a file
number.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/c_pFEM.dir/build.make CMakeFiles/c_pFEM.dir/number.cpp.s
.PHONY : number.cpp.s

volumes.o: volumes.cpp.o

.PHONY : volumes.o

# target to build an object file
volumes.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/c_pFEM.dir/build.make CMakeFiles/c_pFEM.dir/volumes.cpp.o
.PHONY : volumes.cpp.o

volumes.i: volumes.cpp.i

.PHONY : volumes.i

# target to preprocess a source file
volumes.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/c_pFEM.dir/build.make CMakeFiles/c_pFEM.dir/volumes.cpp.i
.PHONY : volumes.cpp.i

volumes.s: volumes.cpp.s

.PHONY : volumes.s

# target to generate assembly for a file
volumes.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/c_pFEM.dir/build.make CMakeFiles/c_pFEM.dir/volumes.cpp.s
.PHONY : volumes.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... c_pFEM"
	@echo "... cpFEM.o"
	@echo "... cpFEM.i"
	@echo "... cpFEM.s"
	@echo "... create.o"
	@echo "... create.i"
	@echo "... create.s"
	@echo "... draw.o"
	@echo "... draw.i"
	@echo "... draw.s"
	@echo "... fields.o"
	@echo "... fields.i"
	@echo "... fields.s"
	@echo "... linear_aux.o"
	@echo "... linear_aux.i"
	@echo "... linear_aux.s"
	@echo "... linear_vect_to_field.o"
	@echo "... linear_vect_to_field.i"
	@echo "... linear_vect_to_field.s"
	@echo "... move.o"
	@echo "... move.i"
	@echo "... move.s"
	@echo "... number.o"
	@echo "... number.i"
	@echo "... number.s"
	@echo "... volumes.o"
	@echo "... volumes.i"
	@echo "... volumes.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

